// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BidderId")
                        .HasColumnType("int");

                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 550,
                            BidTime = new DateTime(2024, 7, 12, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3635),
                            BidderId = 1,
                            LotId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 600,
                            BidTime = new DateTime(2024, 7, 13, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3649),
                            BidderId = 3,
                            LotId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 700,
                            BidTime = new DateTime(2024, 7, 14, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3654),
                            BidderId = 2,
                            LotId = 1
                        });
                });

            modelBuilder.Entity("Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toys & Hobbies"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Musical Instruments"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Data.Entities.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<int>("BidCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HighestBid")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastRate")
                        .HasColumnType("int");

                    b.Property<int?>("MinBidIncrement")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RateStep")
                        .HasColumnType("int");

                    b.Property<int?>("SellerMinPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartOfBidding")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Lots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Latest model",
                            HighestBid = 0,
                            ImageUrl = "https://cdn.new-brz.net/app/public/models/MQAG2/large/w/180413170205345780.webp",
                            LastRate = 650,
                            MinBidIncrement = 50,
                            Name = "iPhone X",
                            Quantity = 5,
                            RateStep = 10,
                            StartOfBidding = new DateTime(2024, 7, 18, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3172),
                            StartPrice = 500
                        },
                        new
                        {
                            Id = 2,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 2,
                            Description = "Strength training",
                            HighestBid = 0,
                            ImageUrl = "https://powerball.ua/content/images/46/480x480l50nn0/kystovyi-trenazher-powerball-e-titan-pro-electric-start-85723670147321.jpg",
                            LastRate = 45,
                            MinBidIncrement = 5,
                            Name = "PowerBall",
                            Quantity = 3,
                            RateStep = 5,
                            StartOfBidding = new DateTime(2024, 7, 22, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3338),
                            StartPrice = 20
                        },
                        new
                        {
                            Id = 3,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 3,
                            Description = "Comfortable sportswear",
                            HighestBid = 0,
                            ImageUrl = "https://lh5.googleusercontent.com/proxy/mMh-P0oMHtmHlosJf4VKCNQEIq6201qQb8iaWP39c24dFaWNo8rM8EOVQevKbhc8vOrMbmCUJYR_PEfdrx4MVqd5dlIggBUvJmUSTKO2JnI",
                            LastRate = 189,
                            MinBidIncrement = 10,
                            Name = "Nike T-Shirt",
                            Quantity = 3,
                            RateStep = 15,
                            StartOfBidding = new DateTime(2024, 7, 20, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3343),
                            StartPrice = 50
                        },
                        new
                        {
                            Id = 4,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Newest model",
                            HighestBid = 0,
                            ImageUrl = "https://hotline.ua/img/tx/370/3708775135.jpg",
                            LastRate = 1200,
                            MinBidIncrement = 100,
                            Name = "Samsung S23",
                            Quantity = 0,
                            RateStep = 50,
                            StartOfBidding = new DateTime(2024, 7, 27, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3348),
                            StartPrice = 1000
                        },
                        new
                        {
                            Id = 5,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 6,
                            Description = "Toys for kids",
                            HighestBid = 0,
                            ImageUrl = "https://sport.qc.ca/wp-content/uploads/2021/01/dsl-original-images/loi_air18_18_air_ball_ballon_air_18_1486249200_1488836710.jpg",
                            LastRate = 50,
                            MinBidIncrement = 2,
                            Name = "Air Ball",
                            Quantity = 0,
                            RateStep = 5,
                            StartOfBidding = new DateTime(2024, 7, 21, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3353),
                            StartPrice = 10
                        },
                        new
                        {
                            Id = 6,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Powerful laptop",
                            HighestBid = 0,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyR7bUxH63AoIF2_TESOi2pgOgdEn5x4qAYA&s",
                            LastRate = 2300,
                            MinBidIncrement = 200,
                            Name = "MacBook Pro 2019",
                            Quantity = 23,
                            RateStep = 100,
                            StartOfBidding = new DateTime(2024, 7, 31, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3513),
                            StartPrice = 2000
                        },
                        new
                        {
                            Id = 7,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 2,
                            Description = "Older model",
                            HighestBid = 0,
                            ImageUrl = "https://remont2.lvivservice.com.ua/upload/iblock/b39/S4.png",
                            LastRate = 440,
                            MinBidIncrement = 10,
                            Name = "Samsung S4",
                            Quantity = 0,
                            RateStep = 20,
                            StartOfBidding = new DateTime(2024, 7, 19, 20, 3, 32, 660, DateTimeKind.Local).AddTicks(3521),
                            StartPrice = 100
                        });
                });

            modelBuilder.Entity("Data.Entities.Bid", b =>
                {
                    b.HasOne("Data.Entities.Lot", "Lot")
                        .WithMany("Bids")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Data.Entities.Lot", b =>
                {
                    b.HasOne("Data.Entities.Category", "Category")
                        .WithMany("Lots")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Data.Entities.Category", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Data.Entities.Lot", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
