// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAuction.Data;

#nullable disable

namespace WebAuction.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20240705184406_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAuction.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BidderId")
                        .HasColumnType("int");

                    b.Property<int?>("LotId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 550m,
                            BidTime = new DateTime(2024, 6, 30, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(290),
                            BidderId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 600m,
                            BidTime = new DateTime(2024, 7, 1, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(301),
                            BidderId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 700m,
                            BidTime = new DateTime(2024, 7, 2, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(306),
                            BidderId = 2,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("WebAuction.Entityes.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toys & Hobbies"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Musical Instruments"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("WebAuction.Entityes.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BidCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HighestBid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAuctionActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LastRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinBidIncrement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RateStep")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellerMinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Lots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Latest model",
                            EndTime = new DateTime(2024, 7, 12, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(97),
                            HighestBid = 0m,
                            IsAuctionActive = true,
                            LastRate = 650m,
                            MinBidIncrement = 50m,
                            Name = "iPhone X",
                            Quantity = 5,
                            RateStep = 10,
                            StartPrice = 500m
                        },
                        new
                        {
                            Id = 2,
                            BidCount = 0,
                            CategoryId = 2,
                            Description = "Strength training",
                            EndTime = new DateTime(2024, 7, 10, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(195),
                            HighestBid = 0m,
                            IsAuctionActive = true,
                            LastRate = 45.5m,
                            MinBidIncrement = 5m,
                            Name = "PowerBall",
                            Quantity = 3,
                            RateStep = 5,
                            StartPrice = 20m
                        },
                        new
                        {
                            Id = 3,
                            BidCount = 0,
                            CategoryId = 3,
                            Description = "Comfortable sportswear",
                            EndTime = new DateTime(2024, 7, 8, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(201),
                            HighestBid = 0m,
                            IsAuctionActive = true,
                            LastRate = 189m,
                            MinBidIncrement = 10m,
                            Name = "Nike T-Shirt",
                            Quantity = 3,
                            RateStep = 15,
                            StartPrice = 50m
                        },
                        new
                        {
                            Id = 4,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Newest model",
                            EndTime = new DateTime(2024, 7, 15, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(207),
                            HighestBid = 0m,
                            IsAuctionActive = true,
                            LastRate = 1200m,
                            MinBidIncrement = 100m,
                            Name = "Samsung S23",
                            Quantity = 0,
                            RateStep = 50,
                            StartPrice = 1000m
                        },
                        new
                        {
                            Id = 5,
                            BidCount = 0,
                            CategoryId = 6,
                            Description = "Toys for kids",
                            EndTime = new DateTime(2024, 7, 9, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(212),
                            HighestBid = 0m,
                            IsAuctionActive = true,
                            LastRate = 50m,
                            MinBidIncrement = 2m,
                            Name = "Air Ball",
                            Quantity = 0,
                            RateStep = 5,
                            StartPrice = 10m
                        },
                        new
                        {
                            Id = 6,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Powerful laptop",
                            EndTime = new DateTime(2024, 7, 19, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(220),
                            HighestBid = 0m,
                            IsAuctionActive = true,
                            LastRate = 2300m,
                            MinBidIncrement = 200m,
                            Name = "MacBook Pro 2019",
                            Quantity = 23,
                            RateStep = 100,
                            StartPrice = 2000m
                        },
                        new
                        {
                            Id = 7,
                            BidCount = 0,
                            CategoryId = 2,
                            Description = "Older model",
                            EndTime = new DateTime(2024, 7, 7, 21, 44, 6, 111, DateTimeKind.Local).AddTicks(226),
                            HighestBid = 0m,
                            IsAuctionActive = true,
                            LastRate = 440m,
                            MinBidIncrement = 10m,
                            Name = "Samsung S4",
                            Quantity = 0,
                            RateStep = 20,
                            StartPrice = 100m
                        });
                });

            modelBuilder.Entity("WebAuction.Entities.Bid", b =>
                {
                    b.HasOne("WebAuction.Entityes.Lot", "Lot")
                        .WithMany("Bids")
                        .HasForeignKey("LotId");

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("WebAuction.Entityes.Lot", b =>
                {
                    b.HasOne("WebAuction.Entityes.Category", "Category")
                        .WithMany("Lots")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebAuction.Entityes.Category", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("WebAuction.Entityes.Lot", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
