// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAuction.Data;

#nullable disable

namespace WebAuction.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAuction.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BidderId")
                        .HasColumnType("int");

                    b.Property<int?>("LotId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 550m,
                            BidTime = new DateTime(2024, 7, 10, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(763),
                            BidderId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 600m,
                            BidTime = new DateTime(2024, 7, 11, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(775),
                            BidderId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 700m,
                            BidTime = new DateTime(2024, 7, 12, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(780),
                            BidderId = 2,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("WebAuction.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toys & Hobbies"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Musical Instruments"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("WebAuction.Entities.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<int>("BidCount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestBid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAuctionActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LastRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinBidIncrement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RateStep")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellerMinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartOfBidding")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Lots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Latest model",
                            HighestBid = 0m,
                            ImageUrl = "https://cdn.new-brz.net/app/public/models/MQAG2/large/w/180413170205345780.webp",
                            IsAuctionActive = true,
                            LastRate = 650m,
                            MinBidIncrement = 50m,
                            Name = "iPhone X",
                            Quantity = 5,
                            RateStep = 10,
                            StartOfBidding = new DateTime(2024, 7, 16, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(560),
                            StartPrice = 500m
                        },
                        new
                        {
                            Id = 2,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 2,
                            Description = "Strength training",
                            HighestBid = 0m,
                            ImageUrl = "https://powerball.ua/content/images/46/480x480l50nn0/kystovyi-trenazher-powerball-e-titan-pro-electric-start-85723670147321.jpg",
                            IsAuctionActive = true,
                            LastRate = 45.5m,
                            MinBidIncrement = 5m,
                            Name = "PowerBall",
                            Quantity = 3,
                            RateStep = 5,
                            StartOfBidding = new DateTime(2024, 7, 20, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(655),
                            StartPrice = 20m
                        },
                        new
                        {
                            Id = 3,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 3,
                            Description = "Comfortable sportswear",
                            HighestBid = 0m,
                            ImageUrl = "https://lh5.googleusercontent.com/proxy/mMh-P0oMHtmHlosJf4VKCNQEIq6201qQb8iaWP39c24dFaWNo8rM8EOVQevKbhc8vOrMbmCUJYR_PEfdrx4MVqd5dlIggBUvJmUSTKO2JnI",
                            IsAuctionActive = true,
                            LastRate = 189m,
                            MinBidIncrement = 10m,
                            Name = "Nike T-Shirt",
                            Quantity = 3,
                            RateStep = 15,
                            StartOfBidding = new DateTime(2024, 7, 18, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(661),
                            StartPrice = 50m
                        },
                        new
                        {
                            Id = 4,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Newest model",
                            HighestBid = 0m,
                            ImageUrl = "https://hotline.ua/img/tx/370/3708775135.jpg",
                            IsAuctionActive = true,
                            LastRate = 1200m,
                            MinBidIncrement = 100m,
                            Name = "Samsung S23",
                            Quantity = 0,
                            RateStep = 50,
                            StartOfBidding = new DateTime(2024, 7, 25, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(667),
                            StartPrice = 1000m
                        },
                        new
                        {
                            Id = 5,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 6,
                            Description = "Toys for kids",
                            HighestBid = 0m,
                            ImageUrl = "https://sport.qc.ca/wp-content/uploads/2021/01/dsl-original-images/loi_air18_18_air_ball_ballon_air_18_1486249200_1488836710.jpg",
                            IsAuctionActive = true,
                            LastRate = 50m,
                            MinBidIncrement = 2m,
                            Name = "Air Ball",
                            Quantity = 0,
                            RateStep = 5,
                            StartOfBidding = new DateTime(2024, 7, 19, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(673),
                            StartPrice = 10m
                        },
                        new
                        {
                            Id = 6,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 1,
                            Description = "Powerful laptop",
                            HighestBid = 0m,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyR7bUxH63AoIF2_TESOi2pgOgdEn5x4qAYA&s",
                            IsAuctionActive = true,
                            LastRate = 2300m,
                            MinBidIncrement = 200m,
                            Name = "MacBook Pro 2019",
                            Quantity = 23,
                            RateStep = 100,
                            StartOfBidding = new DateTime(2024, 7, 29, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(682),
                            StartPrice = 2000m
                        },
                        new
                        {
                            Id = 7,
                            Archived = false,
                            BidCount = 0,
                            CategoryId = 2,
                            Description = "Older model",
                            HighestBid = 0m,
                            ImageUrl = "https://remont2.lvivservice.com.ua/upload/iblock/b39/S4.png",
                            IsAuctionActive = true,
                            LastRate = 440m,
                            MinBidIncrement = 10m,
                            Name = "Samsung S4",
                            Quantity = 0,
                            RateStep = 20,
                            StartOfBidding = new DateTime(2024, 7, 17, 14, 17, 16, 865, DateTimeKind.Local).AddTicks(688),
                            StartPrice = 100m
                        });
                });

            modelBuilder.Entity("WebAuction.Entities.Bid", b =>
                {
                    b.HasOne("WebAuction.Entities.Lot", "Lot")
                        .WithMany("Bids")
                        .HasForeignKey("LotId");

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("WebAuction.Entities.Lot", b =>
                {
                    b.HasOne("WebAuction.Entities.Category", "Category")
                        .WithMany("Lots")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebAuction.Entities.Category", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("WebAuction.Entities.Lot", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
